<#
.SYNOPSIS
    Setup environment variables for CortexMetaAgent project

.DESCRIPTION
    This script helps you create a .env file for the CortexMetaAgent project.
    It can configure MCP URLs for local development or Cloud Run deployment.

.PARAMETER Environment
    Deployment environment: "local" or "cloud" (default: "cloud")

.PARAMETER GoogleApiKey
    Google API Key for Gemini

.PARAMETER ShowCurrent
    Show current environment variable values

.EXAMPLE
    .\setup-env.ps1 -Environment cloud

.EXAMPLE
    .\setup-env.ps1 -Environment local -GoogleApiKey "your-key"
#>

param(
    [ValidateSet("local", "cloud")]
    [string]$Environment = "cloud",
    
    [string]$GoogleApiKey = "",
    [switch]$ShowCurrent
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

if ($ShowCurrent) {
    Write-Host "Current Environment Variables:" -ForegroundColor Cyan
    Write-Host ""

    Write-Host "MCP_AGENT_INVENTORY_URL: $(if ($env:MCP_AGENT_INVENTORY_URL) { $env:MCP_AGENT_INVENTORY_URL } else { 'NOT SET' })" -ForegroundColor $(if ($env:MCP_AGENT_INVENTORY_URL) { "Green" } else { "Yellow" })
    Write-Host "MCP_REASONING_COST_URL: $(if ($env:MCP_REASONING_COST_URL) { $env:MCP_REASONING_COST_URL } else { 'NOT SET' })" -ForegroundColor $(if ($env:MCP_REASONING_COST_URL) { "Green" } else { "Yellow" })
    Write-Host "GOOGLE_CLOUD_PROJECT: $(if ($env:GOOGLE_CLOUD_PROJECT) { $env:GOOGLE_CLOUD_PROJECT } else { 'NOT SET' })" -ForegroundColor $(if ($env:GOOGLE_CLOUD_PROJECT) { "Green" } else { "Yellow" })
    Write-Host "GOOGLE_API_KEY: $(if ($env:GOOGLE_API_KEY) { 'SET (length: ' + $env:GOOGLE_API_KEY.Length + ')' } else { 'NOT SET' })" -ForegroundColor $(if ($env:GOOGLE_API_KEY) { "Green" } else { "Yellow" })
    Write-Host ""
    
    if (Test-Path ".env") {
        Write-Host ".env file exists" -ForegroundColor Green
    } else {
        Write-Host ".env file does not exist" -ForegroundColor Yellow
    }
    exit 0
}

# Get Cloud Run URLs
Write-Host "Getting Cloud Run service URLs..." -ForegroundColor Cyan

$agentInventoryUrl = ""
$reasoningCostUrl = ""

try {
    $services = gcloud run services list --region us-central1 --project aiagent-capstoneproject --format="value(metadata.name,status.url)" 2>&1
    if ($LASTEXITCODE -eq 0) {
        $services | ForEach-Object {
            $parts = $_ -split "`t"

            if ($parts[0] -eq "mcp-agent-inventory") { $agentInventoryUrl = $parts[1] }
            if ($parts[0] -eq "mcp-reasoning-cost") { $reasoningCostUrl = $parts[1] }
        }
    }
} catch {
    Write-Host "WARNING: Could not retrieve Cloud Run URLs. Using defaults." -ForegroundColor Yellow
}

# Set defaults if not retrieved

if (-not $agentInventoryUrl) { $agentInventoryUrl = "https://mcp-agent-inventory-eqww7tb4kq-uc.a.run.app" }
if (-not $reasoningCostUrl) { $reasoningCostUrl = "https://mcp-reasoning-cost-eqww7tb4kq-uc.a.run.app" }

Write-Host ""

# Check if .env exists
if (Test-Path ".env") {
    Write-Host "WARNING: .env file already exists" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite existing .env file? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Cancelled. Existing .env file preserved." -ForegroundColor Yellow
        exit 0
    }
}

# Get Google API Key
$apiKey = if ($GoogleApiKey) { $GoogleApiKey } else { $env:GOOGLE_API_KEY }
if (-not $apiKey) {
    Write-Host "GOOGLE_API_KEY is required" -ForegroundColor Yellow
    $apiKeySecure = Read-Host "Enter GOOGLE_API_KEY" -AsSecureString
    $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($apiKeySecure)
    $apiKey = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
}

# Set MCP URLs based on environment
if ($Environment -eq "local") {

    $mcpAgentInventoryUrl = "http://localhost:8001"
    $mcpReasoningCostUrl = "http://localhost:8002"
    Write-Host "Configuring for LOCAL development" -ForegroundColor Cyan
} else {

    $mcpAgentInventoryUrl = $agentInventoryUrl
    $mcpReasoningCostUrl = $reasoningCostUrl
    Write-Host "Configuring for CLOUD RUN / Vertex AI deployment" -ForegroundColor Cyan
}

# Create .env file
$envContent = @(
    "# CortexMetaAgent Environment Variables",
    "# Generated by setup-env.ps1",
    "# DO NOT commit this file to version control",
    "",
    "# =============================================================================",
    "# Agent Configuration",
    "# =============================================================================",
    "",
    "AGENT_MODEL=gemini-2.5-flash-lite",
    "",
    "# =============================================================================",
    "# MCP Server URLs",
    "# =============================================================================",
    "# Environment: $Environment",
    "",

    "MCP_AGENT_INVENTORY_URL=$mcpAgentInventoryUrl",
    "MCP_REASONING_COST_URL=$mcpReasoningCostUrl",
    "",
    "# =============================================================================",
    "# Google Cloud Configuration",
    "# =============================================================================",
    "",
    "GOOGLE_CLOUD_PROJECT=aiagent-capstoneproject",
    "GOOGLE_CLOUD_LOCATION=us-central1",
    "GOOGLE_APPLICATION_CREDENTIALS=aiagent-capstoneproject-10beb4eeaf31.json",
    "GOOGLE_API_KEY=$apiKey",
    "",
    "# =============================================================================",
    "# MCP Server Ports (for running servers locally)",
    "# =============================================================================",
    "",

    "PORT_AGENT_INVENTORY=8001",
    "PORT_REASONING_COST=8002"
)

$envContent | Set-Content ".env" -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  .env file created successfully!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Environment: $Environment" -ForegroundColor White

Write-Host "  MCP Agent Inventory URL: $mcpAgentInventoryUrl" -ForegroundColor White
Write-Host "  MCP Reasoning Cost URL: $mcpReasoningCostUrl" -ForegroundColor White
Write-Host ""
Write-Host "For Vertex AI deployment, these URLs will be used by agents." -ForegroundColor Yellow
Write-Host "The .env file is automatically loaded by config.py" -ForegroundColor Cyan

